
services:
  portfolio:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my-portfolio
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - portfolio-network

  # Add development service
  portfolio-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my-portfolio-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge